## Initial Data

In [24]:
import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
print(type(x))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


## For Loops

### Using 2 for loops

In [25]:
for i in x:
    for ii in i:
        if ii>7:
            break
        if ii % 2 == 0:
            continue
        print (ii)
    

<class 'numpy.ndarray'>
1
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
3
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
5
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
7
<class 'numpy.ndarray'>


### Using ravel to make it into a 1d array first

In [28]:
for i in x.ravel():
    print(type(x))
    if i>7:
         break
    if i % 2 == 0:
         continue
    print (i)

<class 'numpy.ndarray'>
1
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
3
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
5
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
7
<class 'numpy.ndarray'>


## Practice Problems

### converting to farenheit or celcius

In [29]:
temp = input("Input the  temperature you like to convert? (e.g., 45F, 102C etc.) : ")
degree = int(temp[:-1])
i_convention = temp[-1]

if i_convention.upper() == "C":
  result = int(round((9 * degree) / 5 + 32))
  o_convention = "Fahrenheit"
elif i_convention.upper() == "F":
  result = int(round((degree - 32) * 5 / 9))
  o_convention = "Celsius"
else:
  print("Input proper convention.")
  quit()
print("The temperature in", o_convention, "is", result, "degrees.")

Input the  temperature you like to convert? (e.g., 45F, 102C etc.) : 45F
The temperature in Celsius is 7 degrees.


In [ ]:
import random
target_num, guess_num = random.randint(1, 10), 0
while target_num != guess_num:
    guess_num = int(input('Guess a number between 1 and 10 until you get it right : '))
print('Well guessed!')

In [ ]:
word=input('input the word:')

In [ ]:
rev=word[len(word):-len(word)-1:-1]
print(rev)