## Initial Data

In [55]:
import numpy as np
import pandas as pd
import re
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=((1,2,3),(4,5,6),(7,8,9))
print(x)
print(type(x))
z=np.array(y)
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## For Loops

### Using 2 for loops

In [25]:
for i in x:
    for ii in i:
        if ii>7:
            break
        if ii % 2 == 0:
            continue
        print (ii)
    

<class 'numpy.ndarray'>
1
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
3
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
5
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
7
<class 'numpy.ndarray'>


### Using ravel to make it into a 1d array first

In [28]:
for i in x.ravel():
    print(type(x))
    if i>7:
         break
    if i % 2 == 0:
         continue
    print (i)

<class 'numpy.ndarray'>
1
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
3
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
5
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
7
<class 'numpy.ndarray'>


## Practice Problems

### converting to farenheit or celcius

In [29]:
temp = input("Input the  temperature you like to convert? (e.g., 45F, 102C etc.) : ")
degree = int(temp[:-1])
i_convention = temp[-1]

if i_convention.upper() == "C":
  result = int(round((9 * degree) / 5 + 32))
  o_convention = "Fahrenheit"
elif i_convention.upper() == "F":
  result = int(round((degree - 32) * 5 / 9))
  o_convention = "Celsius"
else:
  print("Input proper convention.")
  quit()
print("The temperature in", o_convention, "is", result, "degrees.")

Input the  temperature you like to convert? (e.g., 45F, 102C etc.) : 45F
The temperature in Celsius is 7 degrees.


In [ ]:
import random
target_num, guess_num = random.randint(1, 10), 0
while target_num != guess_num:
    guess_num = int(input('Guess a number between 1 and 10 until you get it right : '))
print('Well guessed!')

In [1]:
word=input('input the word:')

input the word:michaelagung


In [2]:
rev=word[len(word):-len(word)-1:-1]
print(rev)

gnugaleahcim


In [7]:
  
rev=word[index]
print(index)

TypeError: only size-1 arrays can be converted to Python scalars

## Takes two digit input and generate a 2d array

In [32]:
digit=input('Enter a 2 digit number:')
m=int(digit[0])
n=int(digit[-1])
print(type(m))
x=np.zeros([m,n])
for row in range(m):
    for col in range(n):
        x[row][col]=int(row*col)
print(x)

Enter a 2 digit number:99


## built in range vs np.arange (I think it's basically the same)

In [52]:
a=range(9)
b=np.arange(9)
print(a)
print(b)

range(0, 9)
[0 1 2 3 4 5 6 7 8]


## Finding if the string contains any of the letters

In [68]:
a='string'
print(re.search("[a-m]",a))

<_sre.SRE_Match object; span=(3, 4), match='i'>
